import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fa' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 10,
  },
  headerIcon: { fontSize: 28, color: '#333' },
  headerTitle: { fontSize: 18, fontWeight: '600', color: '#555' },
  plantName: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#1e2b3c',
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 20,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  card: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardMoisture: { borderTopWidth: 4, borderTopColor: '#4A90E2' },
  cardHumidity: { borderTopWidth: 4, borderTopColor: '#50E3C2' },
  cardTemp:     { borderTopWidth: 4, borderTopColor: '#F5A623' },
  cardLight:    { borderTopWidth: 4, borderTopColor: '#FF6B6B' },
  cardTitle: { fontSize: 16, color: '#7f8c8d', marginBottom: 4 },
  cardStatus: { fontSize: 14, fontWeight: '600', marginBottom: 8, color: '#2c3e50' },
  cardValue: { fontSize: 28, fontWeight: 'bold', color: '#1e2b3c' },
  hint: {
    textAlign: 'center',
    color: '#95a5a6',
    fontSize: 14,
    marginVertical: 10,
    fontStyle: 'italic',
  },
  footer: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    marginTop: 10,
    alignItems: 'center',
  },
  lastReading: { fontSize: 16, color: '#34495e', marginBottom: 10 },
  helpLink: { fontSize: 18, color: '#3498db', fontWeight: '500' },
  alertBanner: {
    backgroundColor: '#FFEBEE',
    borderLeftWidth: 4,
    borderLeftColor: '#F44336',
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 10,
    borderRadius: 8,
  },
  alertTitle: { fontSize: 18, fontWeight: '600', color: '#B71C1C', marginBottom: 4 },
  alertMessage: { fontSize: 14, color: '#B71C1C', marginTop: 2 },
  soilTempRow: {
    backgroundColor: '#E8F5E9',
    marginHorizontal: 16,
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
  },
  soilTempText: { fontSize: 16, color: '#2E7D32', textAlign: 'center' },
});